### ISSUE TITLE
Interactor.cpp hangs on Linux

### ISSUE THREAD

**Issue by Zuza** [GassaFM/online-exam#3]
When I try to test the provided code, runtwo.py waits indefinitely for interactor to finish. The solution has finished and exited cleanly, but interactor never exits.

Programs used: solution.cpp (unchanged), runtwo.py (unchanged), interactor.cpp (added some debugging output, so line numbers don't match; otherwise unchanged), test_solution.sh (unchanged)

Platform: Ubuntu 14.04.4 LTS; 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Gdb output for interactor:

> # 0  0x00007f2aa5cca6b0 in __read_nocancel () at ../sysdeps/unix/syscall-template.S:81
> # 1  0x00007f2aa5c595a0 in _IO_new_file_underflow (fp=0x7f2aa5f9e640 <_IO_2_1_stdin_>) at fileops.c:613
> # 2  0x00007f2aa5c5a52e in __GI__IO_default_uflow (fp=0x7f2aa5f9e640 <_IO_2_1_stdin_>) at genops.c:435
> # 3  0x00007f2aa5c50ace in _IO_getc (fp=0x7f2aa5f9e640 <_IO_2_1_stdin_>) at getc.c:39
> # 4  0x000000000040e44e in FileInputStreamReader::curChar (this=0x2711520) at testlib.h:1398
> # 5  0x0000000000409e1b in InStream::readStringTo (this=0x61f600 <ouf>, result="") at testlib.h:2799
> # 6  0x0000000000409ed7 in InStream::readString (this=0x61f600 <ouf>) at testlib.h:2819
> # 7  0x000000000040d1c1 in main (argc=4, argv=0x7ffcca89a888) at interactor.cpp:29

**Comment by GassaFM** [comment]
Hmm. Have you used the latest runtwo utility, one with the [patch](https://github.com/GassaFM/online-exam/pull/2/files)? The symptoms are like before the change.

**Comment by Zuza** [comment]
You are right, it works now. I just downloaded the release zip linked in the statement. Thanks

**Comment by GassaFM** [comment]
Thank you for the feedback! I'll publish an updated release in an hour or two.
